### ISSUE TITLE
Docker Manifest from Docker CE 18.05.0

### ISSUE THREAD

**Issue by RaymondMouthaan** [vfarcic/jenkins-shared-libraries#12]
Hi @vfarcic,

Would it be possible to upgrade to docker ce version 18.05.0~ce~3-0~ubuntu within the Jenkins pipeline? 

When this version is installed and booted with the following configuration file.

`$HOME/.docker/config.json`:
```
{
    "experimental": "enabled"
}
```

And also `/etc/docker/daemon.json`:
```
{
    "experimental": true,
    "storage-driver": "overlay2",
    "max-concurrent-downloads": 50,
    "max-concurrent-uploads": 50
}
```

We have have access to `docker manifest` command to create, annotate and push manifest lists to docker hub instead of using current solution via manifest tool. I'v tested this new feature within a different project and works very nice without installing extra tools.

When implemented as requested, I'll do a PR to make use of `docker manifest command` and fix the issue docker-flow/docker-flow-proxy#18.

Thanks,
Ray

**Comment by vfarcic** [comment]
Sorry for not getting back to you earlier. The weekend flew and I still have too many pending tasks. Can you change Packer definition in https://github.com/vfarcic/docker-flow-hub/blob/master/packer/test-cluster.json? That's the one used to create the image that is used to create VMs for builds.

**Comment by RaymondMouthaan** [comment]
Thats okee, it's not an urgent manner.

Before changing anything in the testcluster.json, could you tell me which docker version gets installed by this command?

```
"sudo apt-get install -y docker-ce"
```

Thanks,
Ray

**Comment by vfarcic** [comment]
That's always the latest stable community version. I built a new image this morning and now it's 18.3.

**Comment by RaymondMouthaan** [comment]
Manifest tool is replaced by Docker manifest and dfp lasted has been checked successfully 💯 .

```
$ docker manifest inspect dockerflow/docker-flow-proxy
```

```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 3027,
         "digest": "sha256:ebc85bb572a9845ecdc8ef08424e3c72bb9a2ddcd2713091a9156aed55d26d49",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 3034,
         "digest": "sha256:5d8e72400c132a51e95d2d33016f893022f1cb7f411dcdb98510df1a06ba5265",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      }
   ]
}
```
