### ISSUE TITLE
Need to wrap $USER and $PASS in quotes

### ISSUE THREAD

**Issue by ohnoitsonyo** [vfarcic/jenkins-shared-libraries#5]
While trying this at Jenkins World 2017, I came across the issue with my password being a auto-generated password and breaking your login command. Fixed by wrapping $PASS in single quotes: `'$PASS'`

Full line with fixes:

 `sh "docker login -u '$USER' -p '$PASS'"`

https://github.com/vfarcic/jenkins-shared-libraries/blob/6c19b57fb4ed595e3ceb9439ce42c2fe38786ae0/vars/dockerBuild.groovy#L8

**Comment by vfarcic** [comment]
Thanks for the tip. The change is committed.
